set(_CATKIN_CURRENT_PACKAGE "spawn_ar")
set(spawn_ar_VERSION "0.0.0")
set(spawn_ar_MAINTAINER "user <user@todo.todo>")
set(spawn_ar_PACKAGE_FORMAT "2")
set(spawn_ar_BUILD_DEPENDS )
set(spawn_ar_BUILD_EXPORT_DEPENDS )
set(spawn_ar_BUILDTOOL_DEPENDS "catkin")
set(spawn_ar_BUILDTOOL_EXPORT_DEPENDS )
set(spawn_ar_EXEC_DEPENDS )
set(spawn_ar_RUN_DEPENDS )
set(spawn_ar_TEST_DEPENDS )
set(spawn_ar_DOC_DEPENDS )
set(spawn_ar_URL_WEBSITE "")
set(spawn_ar_URL_BUGTRACKER "")
set(spawn_ar_URL_REPOSITORY "")
set(spawn_ar_DEPRECATED "")